name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [0.0.0, 0.5.0, 0.5.1]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run action
        uses: ./
        with:
          version: ${{ matrix.version }}
