name: CI

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  test-install:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        version:
          - latest
          - 0.0.0
          - 0.5.1
          - v0.0.0
          - v0.5.1

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run action
        uses: ./
        with:
          version: ${{ matrix.version }}
